version: '3'

services:
  # Atlas service, running Nginx to serve the Javascript files.
  atlas:
    build: ${ATLAS_PATH}
    image: ohdsi/atlas
    environment:
      WEBAPI_URL: ${BASE_URL}/WebAPI/
      ATLAS_HOSTNAME: ${HOSTNAME}
    labels:
      - "traefik.http.routers.atlas.rule=PathPrefix(`/atlas`)"
      - "traefik.http.services.atlas.loadbalancer.server.port=80"

  # WebAPI service, running Nginx to serve the Javascript files.
  webapi:
    build: ${WEBAPI_PATH}
    image: ohdsi/webapi
    labels:
      - "traefik.http.routers.webapi.rule=PathPrefix(`/WebAPI`)"
      - "traefik.http.services.webapi.loadbalancer.server.port=8080"
    environment:
      - JAVA_OPTS=-Xmx4g
      - CLASSPATH=":/var/lib/ohdsi/webapi/drivers/*"
      - WEBAPI_URL=${BASE_URL}
      # Specify Spring settings. Any Spring setting that is set in `pom.xml` or your own
      # settings.xml can be replaced with a variable in this list. Replace the periods (.) 
      # in the variable name with underscores (_)
      - env=webapi-postgresql
      - datasource_driverClassName=org.postgresql.Driver
      - datasource_url=jdbc:postgresql://${DATASOURCE_HOST}/${DATASOURCE_DB}
      - datasource_ohdsi_schema=ohdsi
      - datasource_username=${DATASOURCE_USERNAME}
      - datasource_password=${DATASOURCE_PASSWORD}
      - spring_jpa_properties_hibernate_default__schema=ohdsi
      - spring_jpa_properties_hibernate_dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring_batch_repository_tableprefix=ohdsi.BATCH_
      - flyway_datasource_driverClassName=org.postgresql.Driver
      - flyway_datasource_url=jdbc:postgresql://${DATASOURCE_HOST}/${DATASOURCE_DB}
      - flyway_schemas=ohdsi
      - flyway_placeholders_ohdsiSchema=ohdsi
      - flyway_datasource_username=${DATASOURCE_USERNAME}
      - flyway_datasource_password=${DATASOURCE_PASSWORD}
      - flyway_locations=classpath:db/migration/postgresql

  postgresql:
    image: bitnami/postgresql:12.1.0
    volumes:
      - ./postgresql/data:/bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=${DATASOURCE_USERNAME}
      - POSTGRESQL_PASSWORD=${DATASOURCE_PASSWORD}
      - PGPASSWORD=${DATASOURCE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATASOURCE_DB}

  # Host both Atlas and WebAPI from the same port: <hostname>:8080
  traefik:
    image: traefik:2.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --api.insecure=true --providers.docker
    ports:
      - "8080:80"

