define([], function () {

	const entityType = {
		COHORT_DEFINITION: 'COHORT_DEFINITION',
		CONCEPT_SET: 'CONCEPT_SET',
		COHORT_CHARACTERIZATION: 'COHORT_CHARACTERIZATION',
		PATHWAY_ANALYSIS: 'PATHWAY_ANALYSIS',
		FE_ANALYSIS: 'FE_ANALYSIS',
		INCIDENCE_RATE: 'INCIDENCE_RATE',
		SOURCE: 'SOURCE',
		ESTIMATION: 'ESTIMATION',
		PREDICTION: 'PREDICTION',
		REUSABLE: 'REUSABLE'
	};

	return {
		entityType
	};
});
