define(
	[
		'./home/index',
		'./data-sources/index',
		'./vocabulary/index',
		'./concept-sets/index',
		'./cohort-definitions/index',
		'./characterizations/index',
		'./pathways/index',
		'./incidence-rates/index',
		'./profiles/index',
		'./estimation/index',
		'./prediction/index',
		'./jobs/index',
		'./configuration/index',
		'./feedback/index',
	],
	(
		home,
		dataSources,
		vocabulary,
		conceptSets,
		cohortDefinitions,
		characterizations,
		pathways,
		incidenceRates,
		profiles,
		estimation,
		prediction,
		jobs,
		configuration,
		feedback,
	) => {

		// order of nav items in left-nav will appear in the following order:
		return {
			home,
			dataSources,
			vocabulary,
			conceptSets,
			cohortDefinitions,
			characterizations,
			pathways,
			incidenceRates,
			profiles,
			estimation,
			prediction,
			jobs,
			configuration,
			feedback,
		};
	}
);